# Generated by Django 3.2 on 2021-06-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210617_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year')},
        ),
    ]
