# Generated by Django 3.2 on 2021-07-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'last_name', 'birthdate')},
        ),
    ]
