# Generated by Django 3.2 on 2021-06-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genremoviemap',
            unique_together={('movie', 'genre')},
        ),
    ]
