# Generated by Django 3.2 on 2021-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_persona_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(through='movies.Director', to='movies.Persona'),
        ),
    ]
