# Generated by Django 3.2 on 2021-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genremoviemap_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreMovieMap', to='movies.Genre'),
        ),
    ]
