# Generated by Django 3.2 on 2021-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='biography',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
