# Generated by Django 3.2 on 2021-07-27 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_alter_persona_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('account', 'movie')},
        ),
    ]
