# Generated by Django 3.2 on 2021-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_genre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreMovieMap', to='movies.Genre'),
        ),
    ]
