# Generated by Django 3.2 on 2021-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210730_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='movies.GenreMovieMap', to='movies.Genre'),
        ),
    ]
