# Generated by Django 3.2 on 2021-08-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='star',
            name='character',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='type',
        ),
    ]
