# Generated by Django 3.2 on 2021-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, through='movies.GenreMovieMap', to='movies.Genre'),
        ),
    ]
