# Generated by Django 3.2 on 2021-06-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreMovieMap', to='movies.Genre'),
        ),
    ]
