# Generated by Django 3.2 on 2021-06-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20210626_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='movies.movie'),
        ),
    ]
